<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>351fa19b-3f3f-422f-a4b0-acb4fbb3d577</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nvDong_Day3\nvDong_Day3.csproj" />
  </ItemGroup>

</Project>
