<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nvDong_Day3.ServiceDefaults\nvDong_Day3.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Avatar\" />
  </ItemGroup>

</Project>
